[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Configure the hardware pipeline for Octal Flash and Octal PSRAM tracking blocks
board_build.arduino.memory_type = qio_opi 
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43