[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-devkitc-1 ; Generic devkit configuration matches the Super Mini trace layout
framework = arduino
monitor_speed = 115200

; Explicit hardware flags for standard internal memory allocations
build_flags = 
    -DCORE_DEBUG_LEVEL=0